// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CompetitionCategories string
	Competitions          string
	GorpMigrations        string
}{
	CompetitionCategories: "competition_categories",
	Competitions:          "competitions",
	GorpMigrations:        "gorp_migrations",
}
