// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package server

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CompetitionTypeEnum.
const (
	International CompetitionTypeEnum = "international"
	National      CompetitionTypeEnum = "national"
)

// Defines values for GenderEnum.
const (
	Female GenderEnum = "female"
	Male   GenderEnum = "male"
	Mixed  GenderEnum = "mixed"
)

// CompetitionCategoryResult defines model for CompetitionCategoryResult.
type CompetitionCategoryResult struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// CompetitionResult defines model for CompetitionResult.
type CompetitionResult struct {
	Name string `json:"name"`
}

// CompetitionTypeEnum defines model for CompetitionTypeEnum.
type CompetitionTypeEnum string

// CreateCompetitionCommand defines model for CreateCompetitionCommand.
type CreateCompetitionCommand struct {
	CategoryId      openapi_types.UUID  `json:"categoryId"`
	CompetitionType CompetitionTypeEnum `json:"competitionType"`
	Date            string              `json:"date"`
	FederationName  string              `json:"federationName"`
	Gender          GenderEnum          `json:"gender"`
	Name            string              `json:"name"`
	OrganizerName   string              `json:"organizerName"`
	WeaponId        openapi_types.UUID  `json:"weaponId"`
}

// GenderEnum defines model for GenderEnum.
type GenderEnum string

// PostCompetitionsJSONRequestBody defines body for PostCompetitions for application/json ContentType.
type PostCompetitionsJSONRequestBody = CreateCompetitionCommand

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /competitions)
	GetCompetitions(w http.ResponseWriter, r *http.Request)

	// (POST /competitions)
	PostCompetitions(w http.ResponseWriter, r *http.Request)

	// (GET /competitions/categories)
	GetCompetitionsCategories(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /competitions)
func (_ Unimplemented) GetCompetitions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /competitions)
func (_ Unimplemented) PostCompetitions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /competitions/categories)
func (_ Unimplemented) GetCompetitionsCategories(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCompetitions operation middleware
func (siw *ServerInterfaceWrapper) GetCompetitions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCompetitions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostCompetitions operation middleware
func (siw *ServerInterfaceWrapper) PostCompetitions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCompetitions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetCompetitionsCategories operation middleware
func (siw *ServerInterfaceWrapper) GetCompetitionsCategories(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCompetitionsCategories(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/competitions", wrapper.GetCompetitions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/competitions", wrapper.PostCompetitions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/competitions/categories", wrapper.GetCompetitionsCategories)
	})

	return r
}
