openapi: "3.0.0"
info:
  version: 1.0.0
  title: Fencing API
paths:
  /competitions:
    get:
      tags:
        - Competition
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CompetitionResult"
    post:
      tags:
        - Competition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCompetitionCommand"
      responses:
        '200':
          description: todo

  /competitions/categories:
    get:
      tags:
        - Competition
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CompetitionCategoryResult"

  /competitions/weapons:
    get:
      tags:
        - Competition
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WeaponResult"
  
  /competitions/{competitionId}:
    get:
      tags:
        - Competition
      parameters:
        - in: path
          name: competitionId
          schema:
            type: string
            format: uuid
            example: 123e4567-e89b-12d3-a456-426614174000
          required: true
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompetitionResult"

components:
  schemas:
    # base types
    CompetitionResult:
      type: object
      required:
        - name
        - id
        - date
        - competitionType
        - gender
        - weapon
        - category
        - organizerName
        - federationName

      properties:
        id:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        name:
          type: string
          example: "Competition 1"
        organizerName: 
          type: string
          example: "Organizer 1"
        federationName: 
          type: string
          example: "Federation 1"
        date: 
          type: string
          example: "2024-01-01"
        competitionType: 
          $ref: "#/components/schemas/CompetitionTypeEnum"
        gender:
          $ref: "#/components/schemas/GenderEnum"
        weapon:
          $ref: "#/components/schemas/WeaponResult"
        category:
          $ref: "#/components/schemas/CompetitionCategoryResult"

    CreateCompetitionCommand:
      type: object
      required:
        - name
        - organizerName
        - federationName
        - date
        - competitionType
        - gender
        - categoryId
        - weaponId
      properties:
        name:
          type: string
          example: "Test Open 2024"
        organizerName:
          type: string
          example: "SC Praha"
        federationName:
          type: string
          example: "CSS"
        date: 
          type: string
          example: "2024-01-01"
        competitionType: 
          $ref: "#/components/schemas/CompetitionTypeEnum"
        gender:
          $ref: "#/components/schemas/GenderEnum"
        categoryId:
          type: string
          format: uuid
        weaponId:
          type: string
          format: uuid

    CompetitionTypeEnum:
      type: string
      enum: [national, international]
    GenderEnum:
      type: string
      enum: [male, female, mixed]

    CompetitionCategoryResult:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        name:
          type: string
          example: "Category 1"

    WeaponResult:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174000
        name:
          type: string
          example: "Category 1"
    

          
        
        