openapi: "3.0.0"
info:
  version: 1.0.0
  title: Fencing API
paths:
  /competitions:
    get:
      tags:
        - Competition
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CompetitionResult"
    post:
      tags:
        - Competition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCompetitionCommand"
      responses:
        '200':
          description: todo

components:
  schemas:
    # base types
    CompetitionResult:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "Competition 1"
    CreateCompetitionCommand:
      type: object
      required:
        - name
        - organizerName
        - federationName
        - date
        - competitionType
        - gender
        - categoryId
        - weaponId
      properties:
        name:
          type: string
          example: "Test Open 2024"
        organizerName:
          type: string
          example: "SC Praha"
        federationName:
          type: string
          example: "CSS"
        date: 
          type: string
          example: "2024-01-01"
        competitionType: 
          $ref: "#/components/schemas/CompetitionTypeEnum"
        gender:
          $ref: "#/components/schemas/GenderEnum"
        categoryId:
          type: string
          format: uuid
        weaponId:
          type: string
          format: uuid

    CompetitionTypeEnum:
      type: string
      enum: [national, international]
    GenderEnum:
      type: string
      enum: [male, female, mixed]
    

          
        
        