openapi: "3.0.0"
info:
  version: 1.0.0
  title: Fencing API
paths:
  /competitions:
    get:
      tags:
        - Competition
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CompetitionResult"
components:
  schemas:
    # base types
    CompetitionResult:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "Competition 1"